### ISSUE TITLE
Properties().tab() not working instead showing the original id "m_41491_"

### ISSUE THREAD

**Issue by SpaceNerde** [ParchmentMC/Parchment#228]
**Minecraft version:** *1.19*
**Mappings version:** *2023.06.25-1.19.3*

*if i try to do `() -> new Item(new Item.Properties()` and then `.tab` it does not work and instead i have to use `m_41491_`*

**Comment by alcatrazEscapee** [comment]
If you are using Minecraft 1.19, on Minecraft Forge, you cannot use mappings for Minecraft 1.19.3 directly (via the version `2023.06.25-1.19.3`) because this is using the wrong method names for that version. See the note in [Getting Started](https://parchmentmc.org/docs/getting-started) titled "Using Parchment for an older version on a newer MC version":

> **For using Parchment for an older version on a newer MC version**
> ```
> Mapping's MC version-YYYY.MM.DD-Environment MC version
> ```
> Examples:
> 
> - `1.17.1-2021.12.12-1.18`
>   - Minecraft 1.17.1 mappings (`2021.12.12-1.17.1`) in an MC 1.18 environment
> - `1.18.2-2022.08.07-1.19.1`
>   - Minecraft 1.18.2 mappings (`2021.08.07-1.18.2`) in an MC 1.19.1 environment
> - `1.19.2-2022.08.14-1.20`
>    - Minecraft 1.19.2 mappings (`2021.08.14-1.19.2`) in an MC 1.20 environment
