### ISSUE TITLE
Docs for codecs

### ISSUE THREAD

**Issue by rlnt** [ParchmentMC/Parchment#275]
Do you think it would be feasible to add the inofficial docs for codecs to Parchment?
https://kvverti.github.io/Documented-DataFixerUpper/snapshot/com/mojang/serialization/Codec.html

Since codecs are such a complicated topic and not really beginner-friendly for new modders, I think some docs would be very helpful.

**Comment by sciwhiz12** [comment]
Hello!

We can't really add documentation in the form of javadocs to `Codec`s and the like in Parchment, because those exist in the DataFixerUpper library, not in the Minecraft source code. Parchment's scope is confined to the Minecraft source code: parameters and javadocs, as supplemental to Mojmaps.

It is also more technically challenging to supply such javadocs for libraries, because unlike Minecraft, DataFixerUpper is open-source with a sources JAR already published. Injecting javadocs there would be much harder -- not impossible, but quite a lot of difficulty which may not be worth the cost of developing those features.

Neither do we plan to host documentation in the form of prose (tutorials, guides). Hosting and maintaining such documentation would require a fairly active team of writers and documenters, which we don't have the capacity here at ParchmentMC, as well as being above our scope of supplemental javadocs and parameters.

Such prose documentation would perhaps best be left to another team or group of people working across modding platforms, focused on providing quality documentation.

However, I do agree that having understandable and accessible documentation, javadocs or prose, for `Codec`s and the rest of DataFixerUpper is a neat goal to strive for.

**Comment by rlnt** [comment]
Thank you for the quick and detailed reply. It is a pity but understandable that it is not possible to provide the documentation in this case.

A bit unfortunate that Mojang does not provide documentation for the codecs, even though the project is open-source. It was worth a try.
